name: perfect_contacts
description: A Flutter plugin to retrieve contacts with fullName, firstName, lastName, phoneNumber, countryCode, and countryName.
version: 1.0.0+1
homepage: https://example.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.perfect.contacts.perfect_contacts
        pluginClass: PerfectContactsPlugin
      ios:
        pluginClass: PerfectContactsPlugin